### ISSUE TITLE
if message passes container filter it can be filtered by global filters

### ISSUE THREAD

**Issue by underlow** [underlow/tglog#11]
container filters work before global filters, so event can be filtered by global filters even if it passed containter filter

example:
```
logs:
  events:
    include: 
    exclude:

container:
  events:
    include: 
    exclude:
  names:
    include: 
    exclude:

containers:
  container:
    - name: "some container name"
      logs:
        events:
          include: "error"
          exclude:
      container:
        events:
          include: "*"
          exclude:
```

this configuration won't pass any event at all but it is expected that container configuration works independent of global
